# Generated by Django 5.0.6 on 2024-07-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_author_blogcontributors_blog_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='contributors',
        ),
    ]
