# Generated by Django 5.0.6 on 2024-07-19 13:21

from django.db import migrations

def blog_to_user(apps, schema_migration):
    User = apps.get_model('authentication', 'User')
    Blog = apps.get_model('blog', 'Blog')
    Blog_contribution = apps.get_model('blog', 'BlogContributors')

    for blog in Blog.objects.all():
        author = blog.author
        if author:
            blog.contributors.add(author, through_defaults={'contribution': 'Auteur principal'})
            blog.author = None
            blog.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_contributors'),
    ]

    operations = [
        migrations.RunPython(blog_to_user)
    ]
