# Generated by Django 5.0.6 on 2024-07-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240719_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
