# Generated by Django 5.0.6 on 2024-07-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='word_count',
            field=models.IntegerField(null=True),
        ),
    ]
