# Generated by Django 5.0.6 on 2024-07-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_photo_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
