# Generated by Django 5.0.6 on 2024-07-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_photo_uploader_delete_blog_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(upload_to='photo_de_profil_utilisateur/', verbose_name='Photo de profil'),
        ),
    ]
