# Generated by Django 5.0.6 on 2024-07-16 15:32

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(default=pathlib.PurePosixPath('/home/kali/fotoblog/fotoblog/static/Images/default_avatar.png'), upload_to='photo_de_profil_utilisateur/', verbose_name='Photo de profil'),
        ),
    ]
