# Generated by Django 5.0.6 on 2024-07-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_photo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_profil',
            field=models.ImageField(blank=True, upload_to='photo_de_profil_utilisateur/', verbose_name='Photo de profil'),
        ),
    ]
