# Generated by Django 5.0.6 on 2024-07-18 13:10

from django.db import migrations

def create_groups(apps, schema_editor):
    # Get the models
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Get or create permissions
    add_photo = Permission.objects.get(codename='add_photo')
    change_photo = Permission.objects.get(codename='change_photo')
    delete_photo = Permission.objects.get(codename='delete_photo')
    view_photo = Permission.objects.get(codename='view_photo')

    # Create or get the groups
    creators, created = Group.objects.get_or_create(name='creators')
    subscribers, created = Group.objects.get_or_create(name='subscribers')

    # Set permissions for creators
    creators.permissions.set([
        add_photo,
        change_photo,
        delete_photo,
        view_photo,
    ])
    creators.save()

    # Set permissions for subscribers
    subscribers.permissions.set([view_photo])
    subscribers.save()

    # Add users to the appropriate groups based on their role
    for user in User.objects.all():
        if user.role == User.UserRole.CREATOR:
            creators.user_set.add(user)
        elif user.role == User.UserRole.SUBSCRIBER:
            subscribers.user_set.add(user)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_photo_profil'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
